name: ci
on:
  push:
    branches: main
jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push i386
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386
          push: true
          tags: |
            amattioli2/i386-addon-bticino-x8000:latest
      -
        name: Build and push amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            amattioli2/amd64-addon-bticino-x8000:latest
      -
        name: Build and push armhf
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v6
          push: true
          tags: |
            amattioli2/armhf-addon-bticino-x8000:latest
      -
        name: Build and push armv7
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            amattioli2/armhf-addon-bticino-x8000:latest
      -
        name: Build and push aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            amattioli2/aarch64-addon-bticino-x8000:latest 
